name: learn-github-actions
on: 
  push:
    branches: 
      - master
    paths:
      - 'tenant_group_**_prod**' 
jobs:
  check-bats-version:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Trigger workflow repo 1
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: emely3h/github-actions
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: push-to-simba-repo
          client-payload: '{"message":"push to simba repo has occured"}'




      #  run: |
      #   curl -X POST https://api.github.com/repos/emely3h/github-actions/dispatches \
      #   -H 'Accept: application/vnd.github.v3+json' \
      #   -u ${{ secrets.ACCESS_TOKEN }} \
      #   d '{"event_type":"push-to-simba-repo","client_payload":{"message":"push to simba repo has occured"}}'